### ISSUE TITLE
QA Regression svn has outdated jar files

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#799] opened 2017-08-24 15:50 UTC
Ajit, can you update this with the corrected details about what's happening to prevent the regression runs from working properly?  I'd like this issue described in github to explain why we are pushing the release date.

**Comment by georgeajit** [comment] 2017-08-25 01:15
QA nightly regression tests use a previously built Jar file. This Jar file is built every night and copied into MarkLogic SVN QA repository into the ```lib``` folder.

For the 9.0-3 MarkLogic release, with Java Client API on develop branch (5.0-SNAPSHOT), we have an issue with build script that builds and checks the Jar file into SVN.

The nightly regression runs for Java Client API tests started failing when QA switched Jar usage from 4.0.1 to 5.0 in anticipation of 9.0-3 release. The Jar file present in SVN's QA repository under ```lib``` folder  is not getting updated and the use of old Jar file (5.0-SNAPSHOT) causes QA tests to fail during compilation.

Due to the compilation issues, we are unable to get 2 weeks of stability runs and hence there is a need to push the release out.

Build scripts used in producing Jar files for different releases, need to be reviewed, simplified and ported onto a simpler platform such as Jenkins.

**Comment by georgeajit** [comment] 2017-08-28 17:14
Assigned to Shiva to provide simpilfied script and resolution to the issue.

**Comment by sammefford** [comment] 2018-01-03 23:01
Comment from @itsshivaverma: "I think this is resolved now since we have moved to nexus and brand new build scripts. Feel free to assign it back to me if you are seeing any more issues"

**Comment by georgeajit** [comment] 2018-03-28 17:13
This issue is resolved, since the projects have been realigned and the QA test project has a project dependency on MarkLogic Java Client API project.

**Closed** 2020-10-12 21:29 UTC
Labels: Bug, major, ship
