### ISSUE TITLE
Unexpected char when inserting doc with Ü in uri 

### ISSUE THREAD

**Issue by jeremybrunetML** [marklogic/java-client-api#1163] opened 2019-11-20 16:12 UTC
#1008 # Version of MarkLogic Java Client API
'com.marklogic', name: 'marklogic-client-api', version: '5.0.0'

### Version of MarkLogic Server
10.0-2.1

### Java version
java 12.0.1

### OS and version
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G1012

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
        GenericDocumentManager docMgr = DatabaseClientConfiguration.getInstance().getAdminClient().newDocumentManager();
        DocumentWriteSet writeSet = docMgr.newWriteSet();
        StringHandle handle = new StringHandle("{hello:\"test\"}");
        writeSet.add("/CXXXX_Ü_9999.json", handle);
        docMgr.write(writeSet);

### Expected output: What specifically did you expect to happen?
document created in ML

### Alternatives: What else have you tried, actual/expected?
Same issue with datamovementSDK writeBatcher
Works properly with:
- TextDocumentManager
- curl on /v1/documents
- documentInsert()

**Comment by ehennum** [comment] 2019-12-02 18:03
We plan to fix this bug in the next version of the Java API, which should be released concurrent with MarkLogic 10.0-3 (currently scheduled for January).

**Comment by anu3990** [comment] 2019-12-06 22:20
Hi @jeremybrunetML . I was able to duplicate the error and it comes when we use TextDocumentManager as well.

**Comment by ehennum** [comment] 2019-12-10 17:27
Fixing this bug requires a change to the REST API (tracked with internal bug 53915) as well as the Java API.

On the Java API side, it will be necessary to check the server version to determine the syntax supported for the Content-Disposition header.

**Comment by ehennum** [comment] 2019-12-11 17:13
Internal bug 53915 is now committed on the trunk, 10, and 9 branches of the REST API.

**IMPORTANT:** Because the Java API fix depends on a REST API fix, the Java API can only support UTF-8 characters in document URIs for server releases starting with 9.0-12 and 10.0-3 

When writing a batch, the Java API should check whether a document URI consists entirely of characters from the US-ASCII character set. 

If so, the Java API should continue quote the document URI in the current approach for backward compatibility. 

If not, the Java API should percent-encode the document URI according to this format:

    filename*=UTF-8''THE_PERCENT_ENCODED_DOCUMENT_URI;

as in

    filename*=UTF-8''%2FCXXXX_%C3%9C_9999.json;

One way to check the character set is to get an encoder for the US-ASCII character set (which cannot be shared across threads):

`CharsetEncoder asciiEncoder = java.nio.charset.StandardCharsets.US_ASCII.newEncoder()`

Then, call `asciiEncoder.canEncode(THE_DOCUMENT_URI)` to do the check.  Be sure to call `asciiEncoder.reset()` between each call to canEncode().

An alternative technique for checking would be to construct a java.util.regex.Pattern that matches against the POSIX ASCII character class from the start of the value to the end of the value.

The encoding can be implemented with `URLEncoder.encode(THE_DOCUMENT_URI, "UTF-8")`

**Comment by georgeajit** [comment] 2020-01-02 22:33
Test added to DataMovement test ```StringQueryHostBatcherTest```

```
 @Test
  public void testUTF8InUri() throws Exception
  {
        System.out.println("Running testUTF8InUri");
        DatabaseClient clientTmp = null;
        DataMovementManager dmManagerTmp = null;

        try {
          System.out.println("Running testUTF8InUri");

          String[] filenames = { "constraint1.xml", "constraint2.xml", "constraint3.xml", "constraint4.xml", "constraint5.xml" };
          String combinedQueryFileName = "combinedQueryOptionJSON.json";

          clientTmp = getDatabaseClient("eval-user", "x", getConnType());
          dmManagerTmp = clientTmp.newDataMovementManager();

          QueryManager queryMgr = clientTmp.newQueryManager();
          String dataFileDir = dataConfigDirPath + "/data/";
          String combQueryFileDir = dataConfigDirPath + "/combined/";

          // Use WriteBatcher to write the same files.
          WriteBatcher wbatcher = dmManagerTmp.newWriteBatcher();

          wbatcher.withBatchSize(2);
          InputStreamHandle contentHandle1 = new InputStreamHandle();
          contentHandle1.set(new FileInputStream(dataFileDir + filenames[0]));
          InputStreamHandle contentHandle2 = new InputStreamHandle();
          contentHandle2.set(new FileInputStream(dataFileDir + filenames[1]));
          InputStreamHandle contentHandle3 = new InputStreamHandle();
          contentHandle3.set(new FileInputStream(dataFileDir + filenames[2]));
          InputStreamHandle contentHandle4 = new InputStreamHandle();
          contentHandle4.set(new FileInputStream(dataFileDir + filenames[3]));
          InputStreamHandle contentHandle5 = new InputStreamHandle();
          contentHandle5.set(new FileInputStream(dataFileDir + filenames[4]));

          wbatcher.add(filenames[0], contentHandle1);
          wbatcher.add(filenames[1], contentHandle2);
          wbatcher.add(filenames[2], contentHandle3);
          wbatcher.add(filenames[3], contentHandle4);
          wbatcher.add("/CXXXX_Ü_testqa.xml", contentHandle5);

          wbatcher.flushAndWait();

          // get the combined query
          File file = new File(combQueryFileDir + combinedQueryFileName);

          // create a handle for the search criteria
          FileHandle rawHandle = (new FileHandle(file)).withFormat(Format.JSON);
          // create a search definition based on the handle
          RawCombinedQueryDefinition querydef = queryMgr.newRawCombinedQueryDefinition(rawHandle);

          StringBuilder batchResults = new StringBuilder();
          StringBuilder batchFailResults = new StringBuilder();

          // Run a QueryBatcher on the new URIs.
          QueryBatcher queryBatcher1 = dmManagerTmp.newQueryBatcher(querydef);

          queryBatcher1.onUrisReady(batch -> {
            for (String str : batch.getItems()) {
              batchResults.append(str)
                      .append('|');
            }
          });
          queryBatcher1.onQueryFailure(throwable -> {
            System.out.println("Exceptions thrown from callback onQueryFailure");
            throwable.printStackTrace();
            batchFailResults.append("Test has Exceptions");
          });

          dmManagerTmp.startJob(queryBatcher1);
          boolean bJobFinished = queryBatcher1.awaitCompletion(3, TimeUnit.MINUTES);

          if (bJobFinished) {

            if (!batchFailResults.toString().isEmpty() && batchFailResults.toString().contains("Exceptions")) {
              fail("Test failed due to exceptions");
            }

            // Verify the batch results now.
            String[] res = batchResults.toString().split("\\|");
            assertEquals("Number of reults returned is incorrect", 1, res.length);
            assertTrue("URI returned not correct", res[0].trim().contains("/CXXXX_Ü_testqa.xml"));

            // Read the document and assert on the value
            DOMHandle contentHandle = new DOMHandle();
            contentHandle = readDocumentUsingDOMHandle(clientTmp, "/CXXXX_Ü_testqa.xml", "XML");
            Document readDoc = contentHandle.get();
            System.out.println(convertXMLDocumentToString(readDoc));

            assertTrue("Document content returned not correct", readDoc.getElementsByTagName("id").item(0).getTextContent().contains("0026"));
            assertTrue("Document content returned not correct", readDoc.getElementsByTagName("title").item(0).getTextContent().contains("The memex"));
            assertTrue("Document content returned not correct", readDoc.getElementsByTagName("date").item(0).getTextContent().contains("2009-05-05"));
          }
        } catch (Exception e) {
          System.out.println("Exceptions thrown from testUTF8InUri");
          System.out.println(e.getMessage());
          fail("testUTF8InUri mathod failed");
        } finally {
          clientTmp.release();
          clearDB();
        }
      }
```

**Comment by ehennum** [comment] 2020-08-07 18:40
The regression isn't specific to this bug -- see issue 1242 cited above.

**Comment by georgeajit** [comment] 2020-08-11 20:21
Issue is fixed.

**Closed** 2020-10-12 21:27 UTC
Labels: Bug, major, ship
