### ISSUE TITLE
RowRecord getValueAs and getValuesAs methods parameters need clarity

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#451] opened 2016-08-20 17:50 UTC
For a plan of

``` java
ExportablePlan plan2 = p.fromView("opticFunctionalTest", "detail", "qadetail")
                .joinInner(p.fromView("opticFunctionalTest", "master", "qamaster"), 
                           p.on(p.viewCol("qadetail", "masterId"), p.viewCol("qamaster", "id"))
                          )
                 .select(p.viewCol("qadetail", "id"), 
                         p.viewCol("qadetail", "name"), 
                         p.viewCol("qamaster", "id"), 
                         p.viewCol("qamaster", "name")
                         )
                 .orderBy(p.desc(p.viewCol("qadetail", "name")))
                 .offset(1)
                 .limit(3);
```

The test is trying to access the results using RowRecord iterator and using getValueAs() method.
The second parameter type Class<T> does not accept the following:

``` java
String str = record.getValueAs("qamaster.name", String.class ); << Compile error due to types not being applicable
XsStringVal str = record.getValueAs("qamaster.name", XsStringVal .class ); << No Constructor due to it being an interface
XsStringVal str = record.getValueAs("qamaster.name", StringValImpl.class ) << StringValImpl has no access outside
```

Here is the snippet being tried out. 

``` java
RowSet<RowRecord> rowSet = rowMgr.resultRows(plan2);

// Verify RowRecords using Iterator
Iterator<RowRecord> rowItr = rowSet.iterator();

RowRecord record = null;
if(rowItr.hasNext()) {          
    record = rowItr.next(); 
    assertEquals("Element 1 RowSet Iterator value incorrect", 1, record.getInt("qamaster.id"));
    assertEquals("Element 1 RowSet Iterator value incorrect", 5, record.getInt("qadetail.id"));
    assertEquals("Element 1 RowSet Iterator value incorrect", "Detail 5", record.getString("qadetail.name"));
    try {
        XsStringVal str = record.getValueAs("qamaster.name", .class );
                //assertEquals("Element 1 RowSet Iterator value incorrect", "Master 1", str.getString());
}
```

**Comment by ehennum** [comment] 2016-08-22 22:44
To be clear, only the second case -- XsStringVal -- should be work.

A Java primitive is not accepted.  The compile time error is expected and desired.  Use getString() instead.

We don't want to support the third case. The application should never use implementation classes.

**Comment by ehennum** [comment] 2016-08-22 23:12
I can't reproduce this issue.  The following works fine for me.

	@Test
	public void testTemp() {
		Map<String,Object> literalRow = new HashMap<String,Object>();
		literalRow.put("rowNum", 1);
		literalRow.put("city",   "New York");

		@SuppressWarnings("unchecked")
		PlanBuilder.ModifyPlan plan = p.fromLiterals(new Map[]{literalRow});
		RowSet<RowRecord>   rowSet = rowMgr.resultRows(plan);
		Iterator<RowRecord> rowItr = rowSet.iterator();
		RowRecord row = rowItr.next();

		try {
			XsStringVal val = row.getValueAs("city", XsStringVal.class);
			System.out.println(val.getString());
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

I suspect that it was fixed by a recent check in.

I do want to look into whether the implementation can switch to an unchecked Exception.

**Comment by georgeajit** [comment] 2016-08-26 01:05
Works with ```XsStringVal.class```

**Closed** 2016-11-02 17:10 UTC
Labels: Bug, minor, ship
