### ISSUE TITLE
Add gradle tasks for cook book examples and make it a tool 

### ISSUE THREAD

**Issue by vivekmuniyandi** [marklogic/java-client-api#886] opened 2018-02-06 18:47 UTC
After converting the maven project to gradle #877 - we can define gradle tasks to call the existing DMSDK cookbook examples to actually perform operations like a tool rather than serving as a cook book example. Have the customer give in arguments and execute things as a tool

**Comment by ehennum** [comment] 2020-10-12 18:59
Duplicate of #922

**Closed by ehennum** 2020-10-12 18:59 UTC
Labels: Task, closed, major, new
