### ISSUE TITLE
DMSDK Export Listener leaves too many files open during read/export

### ISSUE THREAD

**Issue by chiamarc** [marklogic/java-client-api#494] opened 2016-10-06 21:00 UTC
This happened in the past with the Java bulk API on Linux.

During dmsdk test runs where we read 100,000 documents from the database, larger batch sizes (100 and above) result in hundreds of thousands of temp files being opened and not closed until the test is shutdown.  This results in a shortage of open file descriptors.  In one case (batches of size 500), more than 1.2M descriptors were open simultaneously.  Telltale signs are a plethora of messages like this:

```
INFO: File /tmp/MIME7250643930506885814.tmp was not deleted
Sep 27, 2016 2:44:38 PM org.jvnet.mimepull.WeakDataFile close
```

This is confirmed by counting the number of open files with lsof and grepping for "MIME".

Libraries:

client-api-java-4.0-20160916
data-movement-1.0-SNAPSHOT.jar (20160922)

**Comment by sammefford** [comment] 2016-10-06 22:10
What is your hard and soft ulimit set to?  You can find out with "ulimit -Hn" and "ulimit -Sn".

How many processes do you have open max at once?  ulimit is applied per-process

Can you say how many "was not deleted" messages you have in your output?

**Comment by chiamarc** [comment] 2016-10-07 01:04
Originally, hard ulimit set to 8192, soft ulimit set to 4096.
I increased both to 100,000 but problem was still occurring:
`Caused by: java.nio.file.FileSystemException: /tmp/MIME7848769172375907673.tmp: Too many open files`
Ulimit is applied per-process as well as system-wide in /etc/security/limits.conf.
When I increased hard and soft to 1,000,000 in limits.conf, the problem disappeared, but I was observing 700K+ open /tmp/MIME* descriptors during any given run via lsof.

For a typical run (reading 100,000 documents from the database in batches of size 500), I see ~78,850 "was not deleted" messages and a peak of ~726K open file descriptors.  It seems like there is around a 10x factor of file descriptors being opened to every single temp file.

**Comment by chiamarc** [comment] 2016-10-07 01:06
I changed the title, because I was not actually reproducing this in the ML9 bulk api.

**Comment by sammefford** [comment] 2016-10-07 14:47
Thanks Marc.  Could you please attach the code, data, and instructions ([mvce](http://stackoverflow.com/help/mcve))?  I'll need to duplicate this scenario.

**Comment by jmakeig** [comment] 2016-10-07 16:15
@chiamarc Is perf harness part checked into this repo?

**Comment by sammefford** [comment] 2017-04-06 22:38
I think this is likely related to #108 since I wasn't in ExportListener calling the close() method on DocumentPage.  We'll try that and see if that fixes the issue.

**Comment by chiamarc** [comment] 2017-04-07 08:31
I can verify that fix #494 is keeping far fewer files open.  The consumers of the API should still be made aware that ulimits for # of open files may need to be increased beyond 64K as I'm still seeing quite a few left open.  Sam, when can the fix go into nightlys/release?

**Comment by jmakeig** [comment] 2017-04-07 14:40
Is this related to Jersey or one if its dependencies?

**Comment by sammefford** [comment] 2017-04-07 15:48
Yes, mime-pull is a dependency of Jersey.  It opens temp files when parsing/downloading multipart responses.  I believe it does so responsibly and cleans up the temp files when we do our part and close our connections.  Nevertheless, as Marc points out, we've had to increase the OS allowable number of open files under heavy load because of these temp files.

**Comment by sammefford** [comment] 2017-04-07 17:12
@georgeajit once I add this fix to the develop and the release-4.0.1 branches, please just monitor for regressions

**Comment by georgeajit** [comment] 2017-04-07 17:22
Sure. But we do see /tmp having tmp files left behind as of now in 4.0.1

**Comment by sammefford** [comment] 2017-04-07 17:37
@georgeajit if you force quit the JVM in the middle of receiving multipart responses, you will see the /tmp/MIME*.tmp files.  If you encounter those files when you have shut down the JVM cleanly, please file a bug report so we can duplicate it and fix it.  I'm aware of #680 which also leaves a tmp file.

**Comment by sammefford** [comment] 2017-07-12 21:16
@georgeajit looks like this has shipped.  Please re-open if I'm wrong.

**Closed by sammefford** 2017-07-12 21:16 UTC
Labels: Bug, major, ship

**Comment by chiamarc** [comment] 2017-07-12 23:28
The DMSDK is still having problems, ostensibly because of this.  Shiva and I will be diagnosing tomorrow and let you know if this needs to be re-opened.
