### ISSUE TITLE
Trying to apply transform to WriteBatcher throws server-side exception

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic/java-client-api#571] opened 2016-12-01 15:30 UTC
```java
 ServerTransform serverTransform = new ServerTransform(transform);

        WriteBatcher whb = dataMovementManager.newWriteBatcher()
                .withBatchSize(100)
                .withThreadCount(20)
                .withTransform(serverTransform)
                .onBatchSuccess((batch) -> {
                    logger.debug("batch # {}, so far: {}", batch.getJobBatchNumber(), batch.getJobWritesSoFar());
                })
                .onBatchFailure((batch,throwable) -> throwable.printStackTrace() );
```
My transform successfully deployed and tested independently over REST API call.
Also, applying the same transform to `XmlDocumentManager.write(...)` works flawlessly. 

Exception thrown:

```
com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: XDMP-AS: (err:XPTY0004) $input-type as xs:string -- Invalid coercion: () as xs:string . See the MarkLogic server error log for further detail.
	at com.marklogic.client.impl.JerseyServices.checkStatus(JerseyServices.java:4257)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3269)
	at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3357)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:618)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:611)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.datamovement.impl.WriteBatcherImpl$BatchWriter.run(WriteBatcherImpl.java:962)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sammefford** [comment] 2016-12-01 15:45
Welcome, Sasha, to the project!  Nice work adapting your code to the latest despite the changes since EA3.  I'm taking a look now that I have your transform, and I'll get back to you shortly.

**Comment by jmakeig** [comment] 2016-12-01 15:46
@sashamitrovich can you please provide the exact version of MarkLogic (`xdmp.version()`) and the Java Client (`git rev-parse HEAD`)?

**Comment by sammefford** [comment] 2016-12-01 16:02
I've verified it on java client api e6e20d7997a158fe17ef8509be7b0436853864ad and server 9.0-20161130

**Comment by jmakeig** [comment] 2016-12-01 16:03
Thanks, @sammefford.

**Comment by sammefford** [comment] 2016-12-01 16:11
Looks like the error is not in DMSDK, but in bulk write.  I can get the same error with this code using bulk write:

**Comment by sammefford** [comment] 2016-12-01 16:15
I'm assigning this to Alex to troubleshoot from the REST layer.

Alex, here's the relevant wire trace showing the single document write (PUT), which works, then the bulk write (POST) which gives the error:

```
[DEBUG] wire - >> "PUT /v1/documents?transform=myTransform&category=content&uri=test1.txt HTTP/1.1[\r][\n]"
[DEBUG] wire - >> "Content-Type: */*[\r][\n]"
[DEBUG] wire - >> "Authorization: Digest username="admin",realm="public",nonce="11a9c7e9984dfdafb9f257ee12f6e750",opaque="41358e97bbdf2bc6",qop=auth,uri="/v1/documents",cnonce="7b92c484",nc=00000002,response="d3078ebb07d296131c6e35ad195a0cd1"[\r][\n]"
[DEBUG] wire - >> "Transfer-Encoding: chunked[\r][\n]"
[DEBUG] wire - >> "Host: 192.168.0.39:8000[\r][\n]"
[DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "4[\r][\n]"
[DEBUG] wire - >> "test"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "0[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - << "HTTP/1.1 204 Content Updated[\r][\n]"
[DEBUG] wire - << "Server: MarkLogic[\r][\n]"
[DEBUG] wire - << "Content-Length: 0[\r][\n]"
[DEBUG] wire - << "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - << "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - << "[\r][\n]"
09:11:16.596 [main] DEBUG c.m.client.impl.JerseyServices - Posting documents
09:11:16.603 [main] DEBUG c.m.client.impl.JerseyServices - Sending multipart for /v1/documents
[DEBUG] wire - >> "POST /v1/documents?transform=myTransform HTTP/1.1[\r][\n]"
[DEBUG] wire - >> "Content-Type: multipart/mixed; boundary=Boundary_1_459848100_1480608676603[\r][\n]"
[DEBUG] wire - >> "Authorization: Digest username="admin",realm="public",nonce="11a9c7e9984dfdafb9f257ee12f6e750",opaque="41358e97bbdf2bc6",qop=auth,uri="/v1/documents",cnonce="47e7dd30",nc=00000003,response="920214266ef749c4da3744cb4ab78839"[\r][\n]"
[DEBUG] wire - >> "Transfer-Encoding: chunked[\r][\n]"
[DEBUG] wire - >> "Host: 192.168.0.39:8000[\r][\n]"
[DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "72[\r][\n]"
[DEBUG] wire - >> "--Boundary_1_459848100_1480608676603[\r][\n]"
[DEBUG] wire - >> "Content-Disposition: attachment; filename="test2.txt"[\r][\n]"
[DEBUG] wire - >> "Content-Type: */*[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "2e[\r][\n]"
[DEBUG] wire - >> "test[\r][\n]"
[DEBUG] wire - >> "--Boundary_1_459848100_1480608676603--[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "0[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - << "HTTP/1.1 500 Internal Server Error[\r][\n]"
[DEBUG] wire - << "Content-type: application/json; charset=UTF-8[\r][\n]"
[DEBUG] wire - << "Server: MarkLogic[\r][\n]"
[DEBUG] wire - << "Content-Length: 258[\r][\n]"
[DEBUG] wire - << "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - << "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - << "[\r][\n]"
[DEBUG] wire - << "{"errorResponse":{"statusCode":500, "status":"Internal Server Error", "messageCode":"INTERNAL ERROR", "message":"XDMP-AS: (err:XPTY0004) $input-type as xs:string -- Invalid coercion: () as xs:string . See the MarkLogic server error log for further detail."}}"
```

**Comment by jmakeig** [comment] 2016-12-01 16:17
@sammefford, any idea why this didn’t show up earlier? Is this a gap in the existing tests?

**Comment by sammefford** [comment] 2016-12-01 16:27
I'm looking into it.  But [this](https://github.com/marklogic/java-client-api/blob/develop/test-complete/src/test/java/com/marklogic/client/functionaltest/TestBulkWriteWithTransformations.java#L141-L191) appears to be doing the same thing but successfully.

**Comment by jmakeig** [comment] 2016-12-01 16:31
The plot thickens…

**Comment by sammefford** [comment] 2016-12-01 16:44
Looks to me like the issue is only when Content-Type: */*.  It works fine when I change my writeSet.add line to this (where I specify the format is text).  It also works fine if the format is set to XML (of course, that's what the TestBulkWriteWithTransformations.testBulkLoadWithXQueryTransform test does).

    writeSet.add("test2.txt", new StringHandle("test").withFormat(Format.TEXT));

Then the wire trace looks like this:

```
[DEBUG] wire - >> "POST /v1/documents?transform=myTransform&trans:value=English&trans:name=Lang HTTP/1.1[\r][\n]"
[DEBUG] wire - >> "Content-Type: multipart/mixed; boundary=Boundary_1_459848100_1480610416451[\r][\n]"
[DEBUG] wire - >> "Authorization: Digest username="admin",realm="public",nonce="6610a669859d7332add14b44e8e3c3ed",opaque="9940f403a18b76a6",qop=auth,uri="/v1/documents",cnonce="0294f046",nc=00000003,response="f47f156c98dfb68becf2a4d59bf8a203"[\r][\n]"
[DEBUG] wire - >> "Transfer-Encoding: chunked[\r][\n]"
[DEBUG] wire - >> "Host: 192.168.0.39:8000[\r][\n]"
[DEBUG] wire - >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "79[\r][\n]"
[DEBUG] wire - >> "--Boundary_1_459848100_1480610416451[\r][\n]"
[DEBUG] wire - >> "Content-Disposition: attachment; filename="test2.txt"[\r][\n]"
[DEBUG] wire - >> "Content-Type: text/plain[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "2e[\r][\n]"
[DEBUG] wire - >> "test[\r][\n]"
[DEBUG] wire - >> "--Boundary_1_459848100_1480610416451--[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - >> "0[\r][\n]"
[DEBUG] wire - >> "[\r][\n]"
[DEBUG] wire - << "HTTP/1.1 200 Bulk Change Written[\r][\n]"
[DEBUG] wire - << "vnd.marklogic.document-format: xml[\r][\n]"
[DEBUG] wire - << "Content-type: application/xml; charset=utf-8[\r][\n]"
[DEBUG] wire - << "Server: MarkLogic[\r][\n]"
[DEBUG] wire - << "Content-Length: 258[\r][\n]"
[DEBUG] wire - << "Connection: Keep-Alive[\r][\n]"
[DEBUG] wire - << "Keep-Alive: timeout=5[\r][\n]"
[DEBUG] wire - << "[\r][\n]"
[DEBUG] wire - << "<rapi:documents xmlns:rapi="http://marklogic.com/rest-api"><rapi:document><rapi:uri>test2.txt</rapi:uri><rapi:category>metadata</rapi:category><rapi:category>content</rapi:category><rapi:mime-type>text/plain</rapi:mime-type></rapi:document></rapi:documents>[\n]"
```

@sashamitrovich can you confirm that you're attempting to call whb.add or whb.addAs with content that doesn't have a clear format?  Ideally, could you share your code that calls whb.add or whb.addAs?

**Comment by sashamitrovich** [comment] 2016-12-02 08:46
My code:
```
 FileInputStream docStream = new FileInputStream(uri);
        InputStreamHandle handle = new InputStreamHandle(docStream);

        DocumentMetadataHandle meta = new DocumentMetadataHandle();
        meta.withCollections("importWithTransform");

        whb.add (uri, meta, handle);
```

The input file:
```
<?xml version="1.0" encoding="UTF-8"?>
<Placemark>
	<name>Zum Adler</name>
	<Point>
		<coordinates>8.6492332,50.1440883</coordinates>
	</Point>
	<ExtendedData>
		<Data name="@id">
			<value>node/32419990</value>
		</Data>
		<Data name="amenity">
			<value>restaurant</value>
		</Data>
		<Data name="cuisine">
			<value>german</value>
		</Data>
		<Data name="microbrewery">
			<value>yes</value>
		</Data>
		<Data name="name">
			<value>Zum Adler</value>
		</Data>
		<Data name="website">
			<value>http://www.zumadler.net/</value>
		</Data>
		<Data name="wheelchair">
			<value>limited</value>
		</Data>
	</ExtendedData>
</Placemark>
```

**Comment by sashamitrovich** [comment] 2016-12-02 08:47
And my transform code:

```
xquery version "1.0-ml";
module namespace dmsdk =
"http://marklogic.com/rest-api/transform/myTransform";

declare function dmsdk:transform(
        $context as map:map,
        $params as map:map,
        $content as document-node())
as document-node()
{
    let $log:=xdmp:log($content)
    let $doc := $content
    let $coordinates:=fn:tokenize($doc/Point/coordinates,",")
    let $newContent:=

            element Poi {
                element type {$doc//Data[@name = "amenity"]/value/text()},
                element coordinate {
                    element lat {$coordinates[2]},
                    element long {$coordinates[1]}
                },
                element name {$doc//Data[@name = "name"]/value/text()},
                element address {
                    element street {$doc//Data[@name = "addr:street"]/value/text()},
                    element housenumber {$doc//Data[@name = "addr:housenumber"]/value/text()},
                    element postcode {$doc//Data[@name = "addr:postcode"]/value/text()},
                    element city {$doc//Data[@name = "addr:city"]/value/text()}
                },
                element website {$doc//Data[@name = "website"]/value/text()},
                element phone {$doc//Data[@name = "phone"]/value/text()},
                element cuisine {$doc//Data[@name = "cuisine"]/value/text()},
                element microbrewery {$doc//Data[@name = "microbrewery"]/value/text()},
                element wheelchair {$doc//Data[@name = "wheelchair"]/value/text()},
                element wheelchair-description {$doc//Data[@name = "wheelchair:description"]/value/text()}
            }

    let $log:=xdmp:log($newContent)
    return document { $newContent }

};
```

**Comment by sashamitrovich** [comment] 2016-12-02 09:02
I can confirm that adding

```
handle.withFormat(Format.XML);
```

to my code **fixes the issue**. I'll leave you to decide whether this is a bug or should just be slightly better documented. Thanks!

**Comment by sammefford** [comment] 2016-12-02 15:49
@sashamitrovich can you tell us what is the value of "uri"? 

I'm thinking this is a bug because if we need you to set the format, we should tell you that, not give a cryptic error.

**Comment by sashamitrovich** [comment] 2016-12-03 12:59
```
private static String uri = "src/test/resources/w1aab7b1.xml";
```

**Comment by sashamitrovich** [comment] 2016-12-07 15:10
I want to confirm similar behaviour for JSON content. If 

```
handle.withFormat(Format.JSON)
```

not specified, the document doesn't get persisted into the db **AND** no error message is thrown server-side.

**Comment by alexmilowski** [comment] 2017-01-09 23:47
I can now reproduce this with:

```
xquery version "1.0-ml";
xdmp:http-post(
   "http://localhost:8000/v1/documents?transform=simple",
   <options xmlns="xdmp:http">
      <authentication method="digest">
         <username>admin</username>
         <password>admin</password>
      </authentication>
      <headers>
         <content-type>multipart/mixed; boundary=xyzzy</content-type>
      </headers>
   </options>,
   xdmp:multipart-encode(
   "xyzzy",
   <manifest>
   <part>
   <headers>
   <Content-Type>*/*</Content-Type>
   <Content-Disposition>attachment; filename="test.txt"</Content-Disposition>
   </headers>
   </part>
   </manifest>,
   document { "test"}
   )
)
```

**Comment by alexmilowski** [comment] 2017-01-09 23:48
The content type isn't being guessed even though the filename parameter has been set.  The failure comes from `Modules/rest-api/models/document-model-update.xqy#3457` as the call to `eput:make-context()` expects a content type at the value is `()`.

The content type should always be guessed from the filename in the `Content-Disposition` header.

**Comment by ehennum** [comment] 2017-03-03 22:12
I believe this was fixed on March 1st under server bug 43944.

Ajit, if you're not the right person to test this issue, please reassign.

**Comment by georgeajit** [comment] 2017-03-09 20:10
Bug 43944 has been shipped. All tests with transforms run fine. However, as for the file extension issue, I have another Bug Track issue filed (44971).

**Closed** 2017-05-03 22:41 UTC
Labels: Bug, closed, major
