### ISSUE TITLE
missing javadoc for PlanBuilderBase.PlanBase and friends

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/java-client-api#757] opened 2017-06-19 23:35 UTC
I tripped over this while trying to figure out if I could export an Optic plan using the Java Client API.  You get 404'd if you try to navigate to the javadoc for PlanBase and some of its sibling interfaces. These bad boys, which show up under PlanBuilder.
```
static interface 	PlanBuilderBase.AccessPlanBase 
static interface 	PlanBuilderBase.ExportablePlanBase 
static interface 	PlanBuilderBase.ModifyPlanBase 
static interface 	PlanBuilderBase.PlanBase 
static interface 	PlanBuilderBase.PreparePlanBase 
```
It's not just some weirdness on docs.marklogic.com as you get the same missing page behavior with a set of static javadocs on the local filesystem. 

To see this in action:
1. Navigate to the PlanBuilder javadoc: http://docs.marklogic.com/javadoc/client/com/marklogic/client/expression/PlanBuilder.html
1. Under the Nested Class Summary, click on one of the above listed interfaces, such as PlanBase.

**Comment by gvaidees** [comment] 2017-06-21 16:16
@sammefford This is targeted for 9.0-2 targeted for next week. Can you please take care of this? Thanks.

**Comment by naliniprakash** [comment] 2017-06-21 19:57
Ganesh, as per our original plan, 3.0.8 is of higher priority to we deliver OKHTTP to JPMC. 4.0.2 is decoupled from 9.0.2.

**Comment by sammefford** [comment] 2017-07-11 17:37
I see that the javadocs are missing from docs.marklogic.com.  I don't know how to reproduce it myself, however.  Can you tell me what command or tool you're using to build the javadocs?  I'm using "mvn javadoc:javadoc" with Java 1.8.0_111.

I'm assigning to Erik to see if he can reproduce.

**Comment by ehennum** [comment] 2017-07-11 17:41
We're not documenting the base types because we don't expect or want people to use the base types.

**Comment by kcoleman-marklogic** [comment] 2017-07-11 17:52
So, when you build locally, do you see all the PlanBuilderBase.* javadoc? Be sure you looking for PlanBuilderBase, not PlanBuilder subtypes. For example, if you go to the page for PlanBuilder.AccessPlan and click on PlanBuildBase.AccessPlanBase in the list of interfaces it extends, does it work?

We build using this command, so I don't think the command line is the issue:
```
mvn -Djavadoc-title="whatever" javadoc:javadoc
```
Which is to say, the only different on the command line is that we override the title so that we can stomp the timestamp.

We build on Windows, not Linux, using Maven 3.3.3 and 1.8.0_102 of the JDK.

**Comment by sammefford** [comment] 2017-07-11 20:29
I'm using Maven 3.2.3 and 1.8.0_72 of the JDK.

> So, when you build locally, do you see all the PlanBuilderBase.* javadoc?

Yes

>  Be sure you looking for PlanBuilderBase, not PlanBuilder subtypes.

Right.

> if you go to the page for PlanBuilder.AccessPlan and click on PlanBuildBase.AccessPlanBase in the list of interfaces it extends, does it work?

Yes

Here's a screenshot

![image](https://user-images.githubusercontent.com/298950/28089164-529e03f4-6645-11e7-8d40-b66e6daa9b6b.png)

**Comment by sammefford** [comment] 2017-07-11 20:31
However, if I understand Erik's recommendation it is that we leave this as-is on docs.marklogic.com

**Comment by kcoleman-marklogic** [comment] 2017-07-11 20:51
That's great in theory, but at least one of those intefaces, ModifyPlanBase, has methods attached. Given that we've chosen not to show inherited methods inline, that means there's no way of knowing about them. If users never need to interact with PlanBuilder.*Plan interface objects directly, then that's fine. Otherwise...

**Comment by sammefford** [comment] 2017-07-11 22:59
Erik, what do you think?  

Side note: Erik probably did this on purpose, but I now realize the reason my javadoc started building properly was because I tried making PlanBuilderBase public.  That did the trick.  I just got distracted and forgot I'd done that so I was confused why it was working for me.

**Comment by ehennum** [comment] 2017-11-30 21:07
It sounds like our choices are to make PlanBuilderBase public or to show inherited methods inline.

Given that PlanBuilderBase is an implementation detail, it would be better to keep it obscure.

Refresh my memory -- is there a reason not to show inherited methods inline?

**Comment by jmakeig** [comment] 2017-11-30 21:18
Isn’t the JavaDoc default *not* to show inherited methods inline? If I’m reading this correctly, why are we trying to outmaneuver JavaDoc? Wouldn’t a Java developer familiar with JavaDoc not expect to see inherited members inline?

**Comment by kcoleman-marklogic** [comment] 2017-11-30 22:33
@jmakeig We have never shown the inherited methods inline in the Java Client API javadoc. (And, yes, I find it mildly annoying as a user.) I don't think we're deliberately perverting the javadoc in any way, though. We don't set many configuration options. It could be it's a peculiarity of the maven javadoc plugin, I suppose.

@ehennum The issue for me regarding the privitization of PlanBuilderBase, et al. is we've ended up "burying" methods like "export" that the user potentially needs. Doesn't it suggest a problem with the class hierarchy?

**Comment by jmakeig** [comment] 2017-11-30 23:01
> perverting the javadoc

Hey, that’s the title of my unfinished memoir.

**Comment by ehennum** [comment] 2017-12-01 00:51
Sending it your way, @sammefford, only to solicit a perspective on the alternatives above.

**Comment by ehennum** [comment] 2017-12-01 00:56
Taking it back -- I should have refreshed the page first.

@kcoleman-marklogic I believe only the JavaDoc is burying the inherited methods.  They are freely available to the Java application.  In other words, we're struggling because JavaDoc is more limited than Java.

Bother.  Frustrating to forced to publicize PlanBuilderBase (which is an implementation detail of PlanBuilder) just because JavaDoc can't handle Java.  But it sounds like that's the only door.

**Comment by ehennum** [comment] 2017-12-01 16:49
Should expose the JavaDoc for the base methods without causing regressions.

If nothing else, this issue has revealed that @jmakeig takes a Marxist-Leninist view ("a problem with the class hierarchy")

**Closed** 2018-05-03 00:11 UTC
Labels: Bug, minor, ship
