### ISSUE TITLE
Java Client API pom.xml doesn't work when Java is upgraded to JDK 11.0.7

### ISSUE THREAD

**Issue by chenfiona** [marklogic/java-client-api#1227] opened 2020-06-12 17:20 UTC
### Version of MarkLogic Java Client API
marklogic-client-api 5.2.0

### Version of MarkLogic Server
MarkLogic 10.0.4

### Java version
JavaSE-11: 
Was 11.0.6 
Upgraded to 11.0.7

###Run `java -version`
`java version "11.0.7" 2020-04-14 LTS`
`Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)`
`Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)`

### Input: Some code to illustrate the problem, preferably in a state that can be independently reproduced on our end
When below lines present in the pom.xml, all of the MarkLogic packages fail:
` <dependencies>`
`  	<dependency>`
  		`<groupId>com.marklogic</groupId>`
  		`<artifactId>marklogic-client-api</artifactId>`
  		`<version>5.2.0</version>`
  	`</dependency>`
 ` </dependencies>`
  `<repositories>`
    `<repository>`
      `<id>jcenter</id>`
      `<url>http://jcenter.bintray.com</url>`
    `</repository>`
`</repositories>`

I don't seem to have this problem BEFORE Java upgrade.  
Can you please advise?  Thank you!

**Comment by ehennum** [comment] 2020-06-12 18:09
Does it work if the POM uses HTTPS instead of HTTP, as in:

     <url>https://jcenter.bintray.com</url>

The packages seem to be present on bintray:

[https://jcenter.bintray.com/com/marklogic/marklogic-client-api/5.2.0/](https://jcenter.bintray.com/com/marklogic/marklogic-client-api/5.2.0/)

**Comment by chenfiona** [comment] 2020-06-12 19:16
Lord! You are good!

> Just this nuance...

![Maven-dependencies](https://user-images.githubusercontent.com/53400797/84538290-63b8ae00-acbf-11ea-916d-75944e8d7aef.jpg)

**Comment by ehennum** [comment] 2020-06-12 19:51
It looks like jcenter switched to requiring HTTPS. 

We'll fix the README to specify https.  Thanks for pointing out the problem.

**Comment by ehennum** [comment] 2020-10-12 19:53
Closing as duplicate of #1206

**Closed by ehennum** 2020-10-12 19:53 UTC
Labels: Bug, fix, minor
