### ISSUE TITLE
can not paging search by QueryManager.

### ISSUE THREAD

**Issue by CS-MakotoNinomiya** [marklogic/java-client-api#823] opened 2017-09-22 06:44 UTC
QueryManagerImpl.java line:162

  @Override
  @SuppressWarnings("unchecked")
  public <T extends SearchReadHandle> T search(QueryDefinition querydef, T searchHandle, long start, Transaction transaction) {
    return search(querydef, searchHandle, 1, transaction, null);
  }

parameter "start" is not used.
version 4.0.2

**Comment by sammefford** [comment] 2017-09-22 17:03
Duplicate of #775 .  The fix will be released wtih 4.0.3

**Closed by sammefford** 2017-09-22 17:03 UTC
