### ISSUE TITLE
Error "No factory for class com.ctc.wstx.evt.WstxEventReader" with Woodstox

### ISSUE THREAD

**Issue by sammefford** [marklogic/java-client-api#390] opened 2016-03-03 15:51 UTC
Woodstox is a popular implementation of XMLEventReader among other things.  But since com.ctc.wstx.evt.WstxEventReader only implements XMLEventReader through two hops, our code doesn't recognize it as implementing XMLEventReader.  Instead we get the following error when we add woodstox to pom.xml by adding:

```
<dependency>
  <groupId>org.codehaus.woodstox</groupId>
  <artifactId>woodstox-core-asl</artifactId>
  <version>4.4.1</version>
</dependency>
```

then run

```
mvn test -Dtest=HandleAsTest
```

we get the following

```
java.lang.IllegalArgumentException: No factory for class com.ctc.wstx.evt.WstxEventReader
    at com.marklogic.client.impl.HandleFactoryRegistryImpl.makeHandle(HandleFactoryRegistryImpl.java:98)
    at com.marklogic.client.impl.DocumentManagerImpl.writeAs(DocumentManagerImpl.java:608)
    at com.marklogic.client.impl.DocumentManagerImpl.writeAs(DocumentManagerImpl.java:575)
    at com.marklogic.client.test.HandleAsTest.testBuiltinReadWrite(HandleAsTest.java:190)
```

Which means DocumentManager.writeAs can't find a handle registered for WstxEventReader or any of the interfaces it implements.

**Comment by sammefford** [comment] 2016-03-03 15:57
This happens because we only look at interfaces directly implemented and [WstxEventReader](http://grepcode.com/file/repo1.maven.org/maven2/org.codehaus.woodstox/wstx-asl/3.2.4/com/ctc/wstx/evt/WstxEventReader.java) only directly implements XMLEventReader2 which in turn implements XMLEventReader.  So it's two hops to get to XMLEventReader, which is a registered class.

I believe the solution is to stop looking at what interfaces the provided class implements and instead run through all the registered classes to see if the provided class isAssignableFrom one of the registered classes.

**Comment by sammefford** [comment] 2016-03-03 16:34
Ajit, this is yet another issue we encountered when adding woodstox to the classpath.  I separated this from #388 because it seems like a different issue to me.  But to test this fix just add woodstox to the classpath / gradle dependencies and you should see errors like the above without this fix and those errors should disappear with this fix.

**Comment by sastafford** [comment] 2016-03-03 18:38
@sammefford I was able to verify the fix using the dev snapshot.  Thanks for the turnaround on this one.  I'm going to go ahead and use the 4.0-snapshot for a while to give you an extra tester.

**Comment by georgeajit** [comment] 2016-03-08 01:09
Tested on three different machines / IDE with the latest git clone. On Mac's Eclipse env, there are no issues. However, on two Windows machines, Eclipse IDE complains on compilation, while building the project. The compilation errors are something like this:
```
The method newFactory() is undefined for the type XMLInputFactory	HandleAsTest.java	/java-client-api-dev/src/test/java/com/marklogic/client/test	line 188	Java Problem
```
It looks like the Maven dependency is not the last one in the order of the build classpath. The JRE System Library was the last one in the order. When Maven Dependencies manually moved to the last; with JRE being on the top of Maven Dependencies,  the compilations errors cleared out.

Sam, assigning this back to you for time being, since .classpath changes do not seem to work at least for Windows.

**Comment by sammefford** [comment] 2016-03-08 16:07
Ajit, I'm not too worried about others' ability to test this.  We can ship as long as we can test it which I can (and I believe you said you can).  We just need to make sure when woodstox ends up on the classpath by some other means our users don't see the same issue.  With this fix in place, I think this issue won't occur for users: https://github.com/marklogic/java-client-api/commit/1ae5bd9463719186e1c631113b17313f10fbf091

**Comment by georgeajit** [comment] 2016-03-09 23:01
Tasks performed on develop branch to validate that adding woodstox to POM and build.gradle files did not have regressions:
1) Updated the pom.xml to have this dependency:
```
<dependency>
	<groupId>org.codehaus.woodstox</groupId>
	<artifactId>woodstox-core-asl</artifactId>
	<version>4.4.1</version>
</dependency>
```
Made sure that there was no woodstox in the local repository.
Then from MarkLogic's QA environment ran the command, to run all of the development team's unit tests. Library woodstox 4.4.1 was downloaded. The compilation went fine.  All tests ran and passed.
```
 make ut tname=java-client-api-unittest-regrsetup.xml
```

2) Updated the build.gradle file in test-complete directory with the following line under the dependency section:
```
compile('org.codehaus.woodstox:woodstox-core-asl:4.4.1')
```
Made sure that local repository did not have woodstox.
Ran the QA tests using gradlew commands. The library was downloaded and the tests ran fine.
``` sh ./gradlew -Dtest.single=TestQueryOptionBuilderGrammar test ```
3) Used the Eclipse IDE with modified POM.xml and build.gradle files (repository already had woodstox library installed) to run QA unit tests

**Closed** 2016-11-02 17:11 UTC
Labels: Bug, major, ship
