### ISSUE TITLE
Missing QName value in Json Document properties 

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#266] opened 2015-03-04 22:14 UTC
A Java test case inserts QName for a JSON document and then reads back the properties.  Here is the snippet of that test case.

I am seeing difference between 7.0 (b2_0) and 8.0 (b3_0) when properties are read back and checked for ns. I checked with Sam and he is not aware of this issue.

After talking with Erik, decided to assign this issue to Erik. 

// put metadata
metadataHandle.getProperties().put(new QName("http://www.example.com", "foo"), "bar"); 
// write the doc with the metadata
writeDocumentUsingOutputStreamHandle(client, filename, "/write-json-outputstreamhandle-metadata/", metadataHandle, "JSON");
// create handle to read metadata
DocumentMetadataHandle readMetadataHandle = new DocumentMetadataHandle();
// read metadata
readMetadataHandle = readMetadataFromDocument(client, "/write-json-outputstreamhandle-metadata/" + filename, "JSON");
// get metadata values
DocumentProperties properties = readMetadataHandle.getProperties();
// Properties
String expectedProperties = "size:1|{http://www.example.com}foo:bar|";
String actualProperties = getDocumentPropertiesString(properties);

In 7.0 Query Console I see the example.com NS missing. Has something changed? The test is looking for example.com to be present.

From 7.0 Query Console:

```
<?xml version="1.0" encoding="UTF-8"?>
<prop:properties xmlns:prop="http://marklogic.com/xdmp/property">
<foo xsi:type="xs:string" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
bar
</foo>
</prop:properties>
```

From 8.0 Query Console:

```
<?xml version="1.0" encoding="UTF-8"?>
<prop:properties xmlns:prop="http://marklogic.com/xdmp/property">
  <foo xsi:type="xs:string" xmlns="http://www.example.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">bar</foo>
</prop:properties>
```

This is a minor issue.

**Comment by ehennum** [comment] 2015-03-05 00:02
Closing because this is a bug in the REST API, not the Java API.

**Comment by sammefford** [comment] 2015-11-06 22:06
It turns out this is in the Java layer, and caused by the fix to #261

**Comment by sammefford** [comment] 2015-11-06 22:12
Here's the test I used to duplicate the issue (and see that the fix worked):

```java
import com.marklogic.client.DatabaseClient;
import com.marklogic.client.DatabaseClientFactory;
import static com.marklogic.client.DatabaseClientFactory.Authentication.DIGEST;
import com.marklogic.client.document.TextDocumentManager;
import com.marklogic.client.io.DocumentMetadataHandle;
import com.marklogic.client.io.DocumentMetadataHandle.DocumentProperties;
import com.marklogic.client.io.StringHandle;
import javax.xml.namespace.QName;

public class PropertiesWriteRead {
    public static void main(String[] args) {
        DatabaseClient client = DatabaseClientFactory.newClient("localhost", 8012, "admin", "admin", DIGEST);
        System.setProperty("org.apache.commons.logging.simplelog.log.org.apache.http.wire", "debug");
        TextDocumentManager docMgr = client.newTextDocumentManager();
        String docUri = "test.txt";
        StringHandle contents = new StringHandle("test");
        docMgr.write(docUri, contents);
        DocumentMetadataHandle metadataHandle = docMgr.readMetadata(docUri, new DocumentMetadataHandle());

        // put metadata
        metadataHandle.getProperties().put(new QName("http://www.example.com", "foo"), "bar");
        // write the doc with the metadata
        docMgr.write(docUri, metadataHandle, contents);
        // read metadata
        DocumentMetadataHandle readMetadataHandle = docMgr.readMetadata(docUri, new DocumentMetadataHandle());
        // get metadata values
        DocumentProperties properties = readMetadataHandle.getProperties();
        // Properties
        String expectedProperties = "size:1|{http://www.example.com}foo:bar|";
System.out.println("DEBUG: [PropertiesWriteRead.java] expectedProperties =[" + expectedProperties  + "]");
System.out.println("DEBUG: [PropertiesWriteRead.java] properties=[" + properties + "]");
    }
}
```

**Comment by georgeajit** [comment] 2015-11-07 00:16
Did a checkout of the latest 2.0-develop and installed ML Server Build 20151106. Ran the test again. The test passes. Issue is fixed.

**Closed** 2016-11-02 17:11 UTC
Labels: Bug, minor, ship
