### ISSUE TITLE
Data movement SDK 's ForestConfigTest JUnit test fails 

### ISSUE THREAD

**Issue by georgeajit** [marklogic/java-client-api#489] opened 2016-10-03 20:59 UTC
Have included the test output from the regression servers' log on 10/03/2016.

```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="1" failures="1" name="com.marklogic.client.test.datamovement.ForestConfigTest" time="0.017" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/home/builder/java/jdk1.8.0_72/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.72-b15"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/space/builder/builds/linux64/HEAD/java-client-api-dev"/>
    <property name="java.runtime.version" value="1.8.0_72-b15"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/home/builder/java/jdk1.8.0_72/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/home/builder/mvn/apache-maven-3.2.5/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value=":.::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="maven.repo.local" value="/space/builder/builds/linux64/HEAD/logs.20161003.0/reg-results/tmp/java-client"/>
    <property name="os.version" value="3.10.0-327.22.2.el7.x86_64"/>
    <property name="user.home" value="/home/buildertest"/>
    <property name="user.timezone" value="America/Los_Angeles"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="buildertest"/>
    <property name="java.class.path" value="/home/builder/mvn/apache-maven-3.2.5/boot/plexus-classworlds-2.5.2.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/home/builder/java/jdk1.8.0_72/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher test -Dmaven.repo.local=/space/builder/builds/linux64/HEAD/logs.20161003.0/reg-results/tmp/java-client"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_72"/>
    <property name="java.ext.dirs" value="/home/builder/java/jdk1.8.0_72/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/home/builder/java/jdk1.8.0_72/jre/lib/resources.jar:/home/builder/java/jdk1.8.0_72/jre/lib/rt.jar:/home/builder/java/jdk1.8.0_72/jre/lib/sunrsasign.jar:/home/builder/java/jdk1.8.0_72/jre/lib/jsse.jar:/home/builder/java/jdk1.8.0_72/jre/lib/jce.jar:/home/builder/java/jdk1.8.0_72/jre/lib/charsets.jar:/home/builder/java/jdk1.8.0_72/jre/lib/jfr.jar:/home/builder/java/jdk1.8.0_72/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/home/builder/mvn/apache-maven-3.2.5"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase classname="com.marklogic.client.test.datamovement.ForestConfigTest" name="testArgs" time="0.017">
    <failure message="expected:&lt;3&gt; but was:&lt;9&gt;" type="java.lang.AssertionError">java.lang.AssertionError: expected:&lt;3&gt; but was:&lt;9&gt;
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.failNotEquals(Assert.java:743)
    at org.junit.Assert.assertEquals(Assert.java:118)
    at org.junit.Assert.assertEquals(Assert.java:555)
    at org.junit.Assert.assertEquals(Assert.java:542)
    at com.marklogic.client.test.datamovement.ForestConfigTest.testArgs(ForestConfigTest.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</failure>
    <system-out>05:20:36.183 [main] DEBUG c.m.client.impl.JerseyServices - Deleting documents
05:20:39.115 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
05:20:39.115 [main] DEBUG c.m.client.impl.JerseyServices - Releasing connection
05:20:39.116 [main] INFO  c.m.client.impl.DatabaseClientImpl - Releasing connection
05:20:39.116 [main] DEBUG c.m.client.DatabaseClientFactory - Creating new database client for server at localhost:8012
05:20:39.116 [main] DEBUG c.m.client.impl.JerseyServices - Connecting to localhost at 8012 as rest-writer
05:20:39.144 [main] DEBUG c.m.client.impl.JerseyServices - Getting forestinfo as application/json
</system-out>
  </testcase>
</testsuite>
```

**Comment by sammefford** [comment] 2016-10-28 18:56
It looks like ForestConfigTest is not a good fit for regression if you're going to run it against a database with 9 forests . . . it expects to be run against the java-unittest database as created by the bootstrap script.  What can we do differently here to make this test work in regression?

**Comment by sammefford** [comment] 2017-03-13 23:23
This should be fixed in the test now.

**Comment by georgeajit** [comment] 2017-03-20 21:13
Test works fine on cluster. Verified on 03192017 nightly regressions.

**Closed** 2017-05-03 22:41 UTC
Labels: Bug, closed, minor
